<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'QueueAdapters\Queue\Service\QueueAdaptersAbstractServiceFactory' => __DIR__ . '/src/QueueAdapters/Queue/Service/QueueAdaptersAbstractServiceFactory.php',
  'QueueAdapters\Module'                                            => __DIR__ . '/Module.php',
);
